export interface Tarefa {
    id_tarefa: number,
    id_ted: number,
    ds_ted: string,
    id_etapa: number,
    ds_etapa: string,
    id_atividade_etapa: number,
    ds_atividade_etapa: string,
    id_atividade_backlog: number,
    ds_atividade_backlog: string,
    ds_tarefa: string,
    id_tarefa_pai: number,
    id_solicitante: number,
    solicitante: string,
    id_responsavel: number,
    responsavel: string,
    id_situacao_tarefa: number | undefined,
    ds_situacao_tarefa: string,
    nr_regra_negocio: string,
    nr_historia_usuario: string,
    tx_observacao: string,
    dt_inicio_tarefa: string,
    dt_fim_tarefa: string,
    dt_inclusao: string
}